# Generated by Django 4.2.1 on 2026-06-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemodel',
            name='state_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
